/**
 * Build.
 *
 * Turns the single source-of-truth dataset into purpose-built artifacts so that
 * no page ever downloads more than it needs:
 *
 *   src/generated/redirect-map.ts    compiled into the edge middleware
 *   dist/data/redirect-map.<hash>    trigger -> template, for the service worker
 *   dist/data/search-index.<hash>    trigger/name/domain/category, for /search
 *
 * Data files are content-hashed so they can be served `immutable` for a year.
 */
import { build as esbuild } from 'esbuild';
import { createHash } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import type { Bang, RedirectMap, SearchEntry } from '../src/lib/types.ts';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const DIST = `${ROOT}dist`;

/** Number of top-relevance bangs inlined into the landing page as a fallback. */
const HOT_BANGS = 200;

const kb = (bytes: number): string => `${(bytes / 1024).toFixed(1)} KB`;
const report = (label: string, body: string): void =>
  console.log(`  ${label.padEnd(34)} ${kb(Buffer.byteLength(body)).padStart(9)}  (${kb(gzipSync(body).length)} gzip)`);

// ---------------------------------------------------------------------------

await rm(DIST, { recursive: true, force: true });
await mkdir(`${DIST}/data`, { recursive: true });
await mkdir(`${DIST}/assets`, { recursive: true });
await mkdir(`${ROOT}src/generated`, { recursive: true });

const bangs: Bang[] = JSON.parse(await readFile(`${ROOT}src/data/bangs.json`, 'utf8'));
// Highest relevance first: the hot set and the search tie-breaker both rely on it.
bangs.sort((a, b) => b.r - a.r || a.t.localeCompare(b.t));
console.log(`Dataset: ${bangs.length} bangs\n`);

/** Writes a file whose name embeds a hash of its contents. */
async function writeHashed(dir: string, name: string, ext: string, body: string): Promise<string> {
  const hash = createHash('sha256').update(body).digest('hex').slice(0, 8);
  const file = `${name}.${hash}.${ext}`;
  await writeFile(`${DIST}/${dir}/${file}`, body);
  report(`${dir}/${file}`, body);
  return `/${dir}/${file}`;
}

console.log('Data artifacts:');

const redirectMap: RedirectMap = Object.fromEntries(bangs.map((bang) => [bang.t, bang.u]));
const redirectMapJson = JSON.stringify(redirectMap);
const redirectMapUrl = await writeHashed('data', 'redirect-map', 'json', redirectMapJson);

const searchIndex: SearchEntry[] = bangs.map((bang) => [bang.t, bang.s, bang.d, bang.c, bang.r]);
const searchIndexUrl = await writeHashed('data', 'search-index', 'json', JSON.stringify(searchIndex));

const hotMap: RedirectMap = Object.fromEntries(bangs.slice(0, HOT_BANGS).map((bang) => [bang.t, bang.u]));

// The middleware bundles the map as a JSON string rather than an object
// literal: V8 parses JSON.parse() of a large payload materially faster than it
// compiles the equivalent literal, which matters on an edge cold start.
await writeFile(
  `${ROOT}src/generated/redirect-map.ts`,
  [
    '// GENERATED BY scripts/build.ts — DO NOT EDIT.',
    '// Regenerate with `npm run build` after changing src/data/bangs.json.',
    "import type { RedirectMap } from '../lib/types.js';",
    '',
    `export const REDIRECT_MAP: RedirectMap = JSON.parse(${JSON.stringify(redirectMapJson)});`,
    '',
  ].join('\n'),
);
report('src/generated/redirect-map.ts', redirectMapJson);

// ---------------------------------------------------------------------------

const BUILD_ID = createHash('sha256').update(redirectMapJson).digest('hex').slice(0, 12);

async function bundle(entry: string, options: { define: Record<string, string>; iife?: boolean }): Promise<string> {
  const result = await esbuild({
    entryPoints: [`${ROOT}src/client/${entry}`],
    bundle: true,
    minify: true,
    write: false,
    format: options.iife ? 'iife' : 'esm',
    target: ['es2022'],
    define: options.define,
    legalComments: 'none',
  });
  return result.outputFiles[0]!.text;
}

console.log('\nScripts:');

const bootJs = await bundle('boot.ts', {
  iife: true,
  define: {
    __HOT_MAP__: JSON.stringify(hotMap),
    __REDIRECT_MAP_URL__: JSON.stringify(redirectMapUrl),
  },
});
report('inline boot (in index.html)', bootJs);

const searchJs = await bundle('search.ts', {
  iife: true,
  define: { __SEARCH_INDEX_URL__: JSON.stringify(searchIndexUrl) },
});
const searchJsUrl = await writeHashed('assets', 'search', 'js', searchJs);

const landingJs = await bundle('landing.ts', { iife: true, define: {} });
const landingJsUrl = await writeHashed('assets', 'landing', 'js', landingJs);

const swJs = await bundle('sw.ts', {
  iife: true,
  define: {
    __REDIRECT_MAP_URL__: JSON.stringify(redirectMapUrl),
    __BUILD_ID__: JSON.stringify(BUILD_ID),
    __PRECACHE__: JSON.stringify(['/', '/search']),
  },
});
// The service worker must live at the root to control the whole origin, and is
// deliberately not hashed — browsers revalidate it by URL.
await writeFile(`${DIST}/sw.js`, swJs);
report('sw.js', swJs);

// ---------------------------------------------------------------------------

console.log('\nPages:');

for (const [source, target] of [
  ['index.html', 'index.html'],
  ['search.html', 'search.html'],
] as const) {
  const html = (await readFile(`${ROOT}src/pages/${source}`, 'utf8'))
    .replace('/*__BOOT__*/', () => bootJs)
    .replaceAll('__SEARCH_JS__', searchJsUrl)
    .replaceAll('__LANDING_JS__', landingJsUrl)
    .replaceAll('__BUILD_ID__', BUILD_ID);
  await writeFile(`${DIST}/${target}`, html);
  report(target, html);
}

console.log('\nBuild complete.');
