/**
 * Build.
 *
 * Turns the single source-of-truth dataset into purpose-built artifacts so that
 * no page ever downloads more than it needs:
 *
 *   src/generated/redirect-map.ts    compiled into the edge middleware
 *   dist/data/redirect-map.<hash>    trigger -> template, for the service worker
 *   dist/data/search-index.<hash>    trigger/name/domain/tags, for the search modal
 *
 * Data files are content-hashed so they can be served `immutable` for a year.
 */
import { build as esbuild } from 'esbuild';
import { createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import type { HomeOverrides, RedirectMap, RedirectPayload, SearchEntry, SearchPayload } from '../src/lib/types.ts';
import { deriveTags } from '../src/lib/tags.ts';
import { loadDataset } from './dataset.ts';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const DIST = `${ROOT}dist`;

/** Number of top-relevance bangs inlined into the landing page as a fallback. */
const HOT_BANGS = 200;

const kb = (bytes: number): string => `${(bytes / 1024).toFixed(1)} KB`;
const report = (label: string, body: string): void =>
  console.log(`  ${label.padEnd(34)} ${kb(Buffer.byteLength(body)).padStart(9)}  (${kb(gzipSync(body).length)} gzip)`);

// ---------------------------------------------------------------------------

await rm(DIST, { recursive: true, force: true });
await mkdir(`${DIST}/data`, { recursive: true });
await mkdir(`${DIST}/assets`, { recursive: true });
await mkdir(`${ROOT}src/generated`, { recursive: true });

const { bangs, upstreamCount, extraCount, overridden } = await loadDataset();
console.log(
  `Dataset: ${bangs.length} bangs ` +
    `(${upstreamCount} upstream + ${extraCount} custom, ${overridden.length} overriding)\n`,
);

/** Writes a file whose name embeds a hash of its contents. */
async function writeHashed(dir: string, name: string, ext: string, body: string): Promise<string> {
  const hash = createHash('sha256').update(body).digest('hex').slice(0, 8);
  const file = `${name}.${hash}.${ext}`;
  await writeFile(`${DIST}/${dir}/${file}`, body);
  report(`${dir}/${file}`, body);
  return `/${dir}/${file}`;
}

console.log('Data artifacts:');

const redirectMap: RedirectMap = Object.fromEntries(bangs.map((bang) => [bang.t, bang.u]));

// Bare-bang destinations. The template's own origin is correct for all but a
// handful of bangs, so only the exceptions are stored.
const stripWww = (host: string): string => host.replace(/^www\./, '').toLowerCase();
const homeOverrides: HomeOverrides = {};
for (const bang of bangs) {
  const domain = bang.d.replace(/^https?:\/\//, '').split('/')[0] ?? '';
  if (!domain) continue;
  try {
    if (stripWww(new URL(bang.u).host) === stripWww(domain)) continue;
  } catch {
    continue;
  }
  homeOverrides[bang.t] = domain.replace(/\/+$/, '');
}

const redirectPayload: RedirectPayload = { map: redirectMap, home: homeOverrides };
const redirectMapJson = JSON.stringify(redirectPayload);
const redirectMapUrl = await writeHashed('data', 'redirect-map', 'json', redirectMapJson);
console.log(`  ${'bare-bang home overrides'.padEnd(34)} ${String(Object.keys(homeOverrides).length).padStart(9)}`);

// Tags are interned: entries carry ids into a shared table rather than
// repeating category strings ~13.5k times.
const tagCounts = new Map<string, number>();
const perBangTags = bangs.map((bang) => {
  const tags = deriveTags(bang);
  for (const tag of tags) tagCounts.set(tag, (tagCounts.get(tag) ?? 0) + 1);
  return tags;
});

const orderedTags = [...tagCounts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
const tagId = new Map(orderedTags.map(([tag], index) => [tag, index]));

const searchPayload: SearchPayload = {
  tags: orderedTags.map(([tag]) => tag),
  entries: bangs.map(
    (bang, index): SearchEntry => [bang.t, bang.s, bang.d, bang.r, perBangTags[index]!.map((tag) => tagId.get(tag)!)],
  ),
};
const searchIndexUrl = await writeHashed('data', 'search-index', 'json', JSON.stringify(searchPayload));
console.log(`  ${'distinct tags'.padEnd(34)} ${String(orderedTags.length).padStart(9)}`);
console.log(`    top: ${orderedTags.slice(0, 12).map(([t, n]) => `${t}(${n})`).join(' ')}`);

// Suggestion index for the OpenSearch endpoint: parallel arrays sorted by
// trigger, so the edge function can binary-search a prefix. Parallel arrays
// compress considerably better than an array of tuples.
const byTrigger = bangs.slice().sort((a, b) => a.t.localeCompare(b.t));
const suggestJson = JSON.stringify({
  t: byTrigger.map((b) => b.t),
  s: byTrigger.map((b) => b.s),
  d: byTrigger.map((b) => b.d),
  r: byTrigger.map((b) => b.r),
});
await writeFile(
  `${ROOT}src/generated/suggest-index.ts`,
  [
    '// GENERATED BY scripts/build.ts — DO NOT EDIT.',
    "import type { SuggestIndex } from '../lib/suggest.js';",
    '',
    `export const SUGGEST_INDEX: SuggestIndex = JSON.parse(${JSON.stringify(suggestJson)});`,
    '',
  ].join('\n'),
);
report('src/generated/suggest-index.ts', suggestJson);

const hotMap: RedirectMap = Object.fromEntries(bangs.slice(0, HOT_BANGS).map((bang) => [bang.t, bang.u]));

// The middleware bundles the map as a JSON string rather than an object
// literal: V8 parses JSON.parse() of a large payload materially faster than it
// compiles the equivalent literal, which matters on an edge cold start.
await writeFile(
  `${ROOT}src/generated/redirect-map.ts`,
  [
    '// GENERATED BY scripts/build.ts — DO NOT EDIT.',
    '// Regenerate with `npm run build` after changing the dataset.',
    "import type { RedirectPayload } from '../lib/types.js';",
    '',
    `const PAYLOAD: RedirectPayload = JSON.parse(${JSON.stringify(redirectMapJson)});`,
    '',
    'export const REDIRECT_MAP = PAYLOAD.map;',
    'export const HOME_OVERRIDES = PAYLOAD.home;',
    '',
  ].join('\n'),
);
report('src/generated/redirect-map.ts', redirectMapJson);

// ---------------------------------------------------------------------------

/**
 * Every emitted artifact, accumulated so the service worker's cache key can be
 * derived from all of them.
 *
 * Keying it off the bang data alone meant a UI-only deploy produced the same
 * cache name, so returning visitors kept being served the previous HTML from
 * the worker's cache indefinitely.
 */
const artifacts: string[] = [redirectMapJson, suggestJson];

async function bundle(
  entry: string,
  options: { define: Record<string, string>; iife?: boolean; jsx?: boolean },
): Promise<string> {
  const result = await esbuild({
    entryPoints: [`${ROOT}src/client/${entry}`],
    bundle: true,
    minify: true,
    write: false,
    format: options.iife ? 'iife' : 'esm',
    target: ['es2022'],
    define: {
      ...options.define,
      // React reads this; without it the bundle keeps all dev-only warnings.
      ...(options.jsx ? { 'process.env.NODE_ENV': '"production"' } : {}),
    },
    ...(options.jsx ? { jsx: 'automatic' as const } : {}),
    legalComments: 'none',
  });
  return result.outputFiles[0]!.text;
}

/** Compiles the Tailwind entry with the standalone CLI. */
async function buildCss(): Promise<string> {
  const output = `${DIST}/assets/.styles.tmp.css`;
  await new Promise<void>((resolve, reject) => {
    const child = spawn(
      process.execPath,
      [`${ROOT}node_modules/@tailwindcss/cli/dist/index.mjs`, '-i', `${ROOT}src/client/styles.css`, '-o', output, '--minify'],
      { stdio: ['ignore', 'ignore', 'inherit'] },
    );
    child.on('error', reject);
    child.on('exit', (code) => (code === 0 ? resolve() : reject(new Error(`tailwind exited ${code}`))));
  });
  const css = await readFile(output, 'utf8');
  await rm(output, { force: true });
  return css;
}

console.log('\nScripts:');

const bootJs = await bundle('boot.ts', {
  iife: true,
  define: {
    __HOT_MAP__: JSON.stringify(hotMap),
    __HOME_OVERRIDES__: JSON.stringify(homeOverrides),
    __REDIRECT_MAP_URL__: JSON.stringify(redirectMapUrl),
  },
});
report('inline boot (in index.html)', bootJs);
artifacts.push(bootJs);

// The search island: React + Radix + cmdk, fetched only when the user opens it.
const modalJs = await bundle('search-modal.tsx', {
  jsx: true,
  define: { __SEARCH_INDEX_URL__: JSON.stringify(searchIndexUrl) },
});
const modalJsUrl = await writeHashed('assets', 'search-modal', 'js', modalJs);
const modalCss = await buildCss();
const modalCssUrl = await writeHashed('assets', 'search-modal', 'css', modalCss);
artifacts.push(modalJs, modalCss);

const landingJs = await bundle('landing.ts', {
  iife: true,
  define: {
    __SEARCH_MODAL_JS__: JSON.stringify(modalJsUrl),
    __SEARCH_MODAL_CSS__: JSON.stringify(modalCssUrl),
  },
});
const landingJsUrl = await writeHashed('assets', 'landing', 'js', landingJs);
artifacts.push(landingJs);

// ---------------------------------------------------------------------------

console.log('\nPages:');

// OpenSearch descriptor. SITE_ORIGIN lets a fork point it at its own domain.
const ORIGIN = process.env['SITE_ORIGIN'] ?? 'https://bang.e108.dev';
const openSearch = `<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/"
                       xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>e108 !Bangs</ShortName>
  <Description>DuckDuckGo-style !bang redirects, resolved at the edge.</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Url type="text/html" method="get" template="${ORIGIN}/?q={searchTerms}"/>
  <Url type="application/x-suggestions+json" method="get" template="${ORIGIN}/suggest?q={searchTerms}"/>
  <moz:SearchForm>${ORIGIN}/</moz:SearchForm>
</OpenSearchDescription>
`;
await writeFile(`${DIST}/opensearch.xml`, openSearch);
report('opensearch.xml', openSearch);
artifacts.push(openSearch);

for (const [source, target] of [['index.html', 'index.html']] as const) {
  const html = (await readFile(`${ROOT}src/pages/${source}`, 'utf8'))
    .replace('/*__BOOT__*/', () => bootJs)
    .replaceAll('__LANDING_JS__', landingJsUrl);
  await writeFile(`${DIST}/${target}`, html);
  report(target, html);
  artifacts.push(html);
}

// ---------------------------------------------------------------------------
// The worker is built last: its cache key is a digest of everything above, so
// any change at all — data, script, style or markup — invalidates it.
// ---------------------------------------------------------------------------

const BUILD_ID = createHash('sha256').update(artifacts.join('\u0000')).digest('hex').slice(0, 12);

const swJs = await bundle('sw.ts', {
  iife: true,
  define: {
    __REDIRECT_MAP_URL__: JSON.stringify(redirectMapUrl),
    __BUILD_ID__: JSON.stringify(BUILD_ID),
    __PRECACHE__: JSON.stringify(['/']),
  },
});
// The service worker must live at the root to control the whole origin, and is
// deliberately not hashed — browsers revalidate it by URL.
await writeFile(`${DIST}/sw.js`, swJs);
report('sw.js', swJs);

console.log(`\nBuild ${BUILD_ID} complete.`);
